// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAddIri66UVlfDO720J9vPtPmgoTuaEFA',
    appId: '1:472117524364:web:db323023bd7aceec6a08a9',
    messagingSenderId: '472117524364',
    projectId: 'physioflow-aee68',
    authDomain: 'physioflow-aee68.firebaseapp.com',
    storageBucket: 'physioflow-aee68.firebasestorage.app',
    measurementId: 'G-5TNLGS6KTM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6WflbmcDhScCdRCNdMyTBdUfCzq50qN4',
    appId: '1:472117524364:android:ef745fb5811b6ef36a08a9',
    messagingSenderId: '472117524364',
    projectId: 'physioflow-aee68',
    storageBucket: 'physioflow-aee68.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL1LERi9ttDWg7XyM7RqdOufLbz7-gW2Y',
    appId: '1:472117524364:ios:b34629dc85c744576a08a9',
    messagingSenderId: '472117524364',
    projectId: 'physioflow-aee68',
    storageBucket: 'physioflow-aee68.firebasestorage.app',
    iosBundleId: 'com.example.physioflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL1LERi9ttDWg7XyM7RqdOufLbz7-gW2Y',
    appId: '1:472117524364:ios:b34629dc85c744576a08a9',
    messagingSenderId: '472117524364',
    projectId: 'physioflow-aee68',
    storageBucket: 'physioflow-aee68.firebasestorage.app',
    iosBundleId: 'com.example.physioflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAddIri66UVlfDO720J9vPtPmgoTuaEFA',
    appId: '1:472117524364:web:6eb041f1f21d7a926a08a9',
    messagingSenderId: '472117524364',
    projectId: 'physioflow-aee68',
    authDomain: 'physioflow-aee68.firebaseapp.com',
    storageBucket: 'physioflow-aee68.firebasestorage.app',
    measurementId: 'G-0VBJE2QT6L',
  );
}
