training:
  epochs: 50
  batch_size: 32
  learning_rate: 0.001
  validation_split: 0.2
  sequence_length: 30
  num_landmarks: 33
  landmark_dims: 4
  model:
    lstm_units: [128, 64]
    dense_units: [32]
  classes:
    - squat
    - leg_raise
    - step_up
  metrics:
    - accuracy
    - precision
    - recall
    - f1